### ISSUE TITLE
Android KOTLIN

### ISSUE THREAD

**Issue by Erchil66** [farmako/flutter_restart#7]
**java.lang.IllegalArgumentException: Unsupported value: 'kotlin.Unit' of type 'class kotlin.Unit'**

this error persist every time i restart

as full code error 

E/flutter ( 6064): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/flutter ( 6064): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:61)
E/flutter ( 6064): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:272)
E/flutter ( 6064): 	at app.farmako.restart.RestartPlugin.onMethodCall(RestartPlugin.kt:27)
E/flutter ( 6064): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 6064): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter ( 6064): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 6064): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 6064): 	at android.os.Handler.handleCallback(Handler.java:958)
E/flutter ( 6064): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 6064): 	at android.os.Looper.loopOnce(Looper.java:205)
E/flutter ( 6064): 	at android.os.Looper.loop(Looper.java:294)
E/flutter ( 6064): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/flutter ( 6064): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 6064): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/flutter ( 6064): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/flutter ( 6064): )
E/flutter ( 6064): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter ( 6064): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)

Steps ----- ON LIFECYCLE----- 
- Make the app on background then with lockscreen
- Go back in the app for more than 3 or 4 minutes
- After Resumed Cycle trigger restart function then this show.

**Comment by alexmercerind** [comment]
Hello @Erchil66,

Thanks a lot for your report. This issue has been resolved in #6. I'll notify you shortly when a new release is published.

FYI: This only shows in the logs, the plugin still works correctly i.e. restart occurs.

Thanks again!

**Comment by Erchil66** [comment]
Hello @alexmercerind 

Thanks for the reply, And Sorry as my reply quite late,

Anyways awesome work about this package. And yeah will close this ticket and awaiting for new release.

Again really thanks.

**Comment by DenisSvinkovskij** [comment]
@alexmercerind Does this issue fixed in the version 1.0.0+1 ? cause I still face the issue
